### ISSUE TITLE
threadAttr.reserved missing field (RTOS2 port on CMSIS 6.0.0)

### ISSUE THREAD

**Issue by markand** [Oryx-Embedded/Common#5]
Hello,

I'm trying to build CycloneTCP using CMSIS-RTOS2 port with RTX v5 version, it looks like the RTOS2 v5 5.8.0 has removed a field in osThreadAttr_t structure because the code fails to compile now:

```
FAILED: CMakeFiles/blink.dir/C_/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common/os_port_cmsis_rtos2.o 
c:\Users\davdem\.vcpkg\artifacts\2139c4c6\compilers.arm.armclang\6.21.0\bin\armclang.exe --target=arm-arm-none-eabi  -Ic:/Users/davdem/Documents/Dev/cmsis/blink/blink/RTE/CMSIS -Ic:/Users/davdem/Documents/Dev/cmsis/blink/blink/RTE/CycloneCommon -Ic:/Users/davdem/Documents/Dev/cmsis/blink/blink/RTE/CycloneTCP -Ic:/Users/davdem/Documents/Dev/cmsis/blink/blink/RTE/Device/LPC1768 -Ic:/Users/davdem/Documents/Dev/cmsis/blink/blink/RTE/_Debug_LPC1768 -IC:/Users/davdem/AppData/Local/arm/packs/ARM/CMSIS-RTX/5.8.0/Include -IC:/Users/davdem/AppData/Local/arm/packs/ARM/CMSIS/6.0.0/CMSIS/Core/Include -IC:/Users/davdem/AppData/Local/arm/packs/ARM/CMSIS/6.0.0/CMSIS/RTOS2/Include -IC:/Users/davdem/AppData/Local/arm/packs/Keil/LPC1700_DFP/2.7.1/Device/Include -IC:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common -IC:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/cyclone_tcp -IC:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/cyclone_tcp/core -IC:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/cyclone_tcp/http -mcpu=Cortex-M3 -mfpu=none -mlittle-endian -DLPC175x_6x -D_RTE_  -g -O0   --target=arm-arm-none-eabi -c -std=gnu11 -Wno-macro-redefined -Wno-pragma-pack -Wno-parentheses-equality -Wno-license-management -isystem "c:/Users/davdem/.vcpkg/artifacts/2139c4c6/compilers.arm.armclang/6.21.0/include" -MD -MT CMakeFiles/blink.dir/C_/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common/os_port_cmsis_rtos2.o -MF CMakeFiles\blink.dir\C_\Users\davdem\AppData\Local\arm\packs\Oryx-Embedded\Middleware\2.3.4\common\os_port_cmsis_rtos2.o.d -o CMakeFiles/blink.dir/C_/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common/os_port_cmsis_rtos2.o -c C:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common/os_port_cmsis_rtos2.c
C:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/common/os_port_cmsis_rtos2.c:96:15: error: no member named 'reserved' in 'osThreadAttr_t'
   96 |    threadAttr.reserved = 0;
      |    ~~~~~~~~~~ ^
1 error generated.
```

I think this is due to CMSIS 6.0.0. It builds with a different error with 5.9.0 but I think this is my configuration missing.

```
C:/Users/davdem/AppData/Local/arm/packs/Oryx-Embedded/Middleware/2.3.4/cyclone_tcp/core/net_mem.c:256:28: error: use of undeclared identifier 'MAX_CHUNK_COUNT'
  256 |    buffer->maxChunkCount = MAX_CHUNK_COUNT;
```
